media: 
  input: src/content/posts/images
  output: ./images
content: 
 - name: posts
   label: Posts
   type: collection
   path: src/content/posts
   filename: "{fields.slug}.md"
   view:
     fields: [title, date] 
   fields:
    - { name: author, label: Author, type: string }
    - { name: date, label: Date, type: date }
    - { name: featured, label: Featured, type: boolean, default: false, hidden: true }
    - { name: image, label: Image, type: image }
    - { name: title, label: Title, type: string }
    - { name: body, label: Body, type: rich-text }
    - { name: slug, label: Slug, type: string, required: true }
        

    